swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /task:
    get:
      operationId: task.read_all
      tags:
        - Task
      summary: Read the entire list of task
      description: Read the list of task
      parameters:
        - name: name
          in: query
          type: string
          description: String to look in name(all_tasks_requested means all)
          required: true
      responses:
        200:
          description: Successfully read task list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                id:
                  type: integer

    post:
      operationId: task.create
      tags:
        - Task
      summary: Create a task and add it to the task list
      description: Create a new task in the task list
      parameters:
        - name: task
          in: body
          description: Task to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: First name of task to create
              id:
                type: integer
                description: Task id
      responses:
        201:
          description: Successfully created task in list

    put:
      operationId: task.update
      tags:
        - Task
      summary: Update a task in the task list
      description: Update a task in the task list
      parameters:
        - name: task
          required: True
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              id:
                type: integer
      responses:
        200:
          description: Successfully updated task in task list

  /task/{id}:
    get:
      operationId: task.read_one
      tags:
        - Task
      summary: Read one task from the task list
      description: Read one task from the task list
      parameters:
        - name: id
          in: path
          description: Last name of the task to get from the list
          type: integer 
          required: True
      responses:
        200:
          description: Successfully read task from task list operation
          schema:
            properties:
              id:
                type: integer
              name:
                type: string

    delete:
      operationId: task.delete
      tags:
        - Task
      summary: Delete a task from the task list
      description: Delete a task
      parameters:
        - name: id
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a task from task list
